site_name: TMEIC Documentation

theme:
  name: material
  features:
    # navigation.tabs
    navigation.sections
    toc.integrate
    navigation.top  search.suggest
    search.highlight
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: red
    accent: black
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to Light mode  
    primary: teal
    accent: lime